;;; markdown-preview-session-tests.el --- Preview regression tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'markdown-preview-session)
(require 'xwidget)

(ert-deftest markdown-preview-session-waits-for-http ()
  (with-temp-buffer
    (let ((attempts 0) (pauses 0))
      (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
                ((symbol-function 'markdown-preview-session--http-ready-p)
                 (lambda (_) (= (cl-incf attempts) 3)))
                ((symbol-function 'accept-process-output)
                 (lambda (&rest _) (cl-incf pauses))))
        (markdown-preview-session--wait "http://127.0.0.1:12345/doc.md")
        (should (= attempts 3))
        (should (= pauses 2))))))

(ert-deftest markdown-preview-session-reports-exit ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'markdown-preview-session--http-ready-p)
               (lambda (_) (ert-fail "Must detect the dead server first"))))
      (should-error (markdown-preview-session--wait "unused") :type 'user-error))))

(ert-deftest markdown-preview-session-times-out ()
  (with-temp-buffer
    (let ((now 0) (markdown-preview-session-timeout 1))
      (cl-letf (((symbol-function 'float-time) (lambda (&rest _) now))
                ((symbol-function 'process-live-p) (lambda (_) t))
                ((symbol-function 'markdown-preview-session--http-ready-p)
                 (lambda (_) nil))
                ((symbol-function 'accept-process-output)
                 (lambda (&rest _) (setq now (+ now 0.5)))))
        (should-error (markdown-preview-session--wait "unused") :type 'user-error)
        (should (= now 1))))))

(ert-deftest markdown-preview-session-http-requires-success ()
  (dolist (status '(200 404 500))
    (let ((response (generate-new-buffer " *preview-test-response*")))
      (with-current-buffer response (setq-local url-http-response-status status))
      (cl-letf (((symbol-function 'url-retrieve-synchronously)
                 (lambda (&rest _) response)))
        (should (eq (markdown-preview-session--http-ready-p "unused")
                    (= status 200)))
        (should-not (buffer-live-p response))))))

(ert-deftest markdown-preview-session-open-starts-waits-and-reopens ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/preview dir/test #1.md")
    (let ((live nil) calls (features (cons 'xwidget-internal features)))
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                ((symbol-function 'process-live-p) (lambda (_) live))
                ((symbol-function 'markdown-preview-session--free-port)
                 (lambda () 20000))
                ((symbol-function 'grip-mode)
                 (lambda (_) (push 'start calls)
                   (should (equal default-directory "/tmp/preview dir/"))
                   (setq grip-mode t live t grip--preview-file buffer-file-name)
                   (grip--preview-1)))
                ((symbol-function 'grip--preview-1)
                 (lambda () (ert-fail "Premature browser launch")))
                ((symbol-function 'markdown-preview-session--wait)
                 (lambda (_) (push 'ready calls)))
                ((symbol-function 'markdown-preview-session--display)
                 (lambda (url)
                   (should (equal url "http://127.0.0.1:20000/test%20%231.md"))
                   (push 'display calls))))
        (markdown-preview-session-open)
        ;; Enabled mode and live server must still reopen the view.
        (markdown-preview-session-open)
        (should (equal (reverse calls) '(start ready display ready display)))
        ;; A stale mode flag must not prevent a dead server from restarting.
        (setq live nil calls nil)
        (markdown-preview-session-open)
        (should (equal (reverse calls) '(start ready display)))))))

(ert-deftest markdown-preview-session-failure-does-not-open-browser ()
  (with-temp-buffer
    (let ((features (cons 'xwidget-internal features)))
      (setq grip--preview-file "/tmp/test.md")
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                ((symbol-function 'process-live-p) (lambda (_) t))
                ((symbol-function 'markdown-preview-session--wait)
                 (lambda (_) (user-error "Server unavailable")))
                ((symbol-function 'markdown-preview-session--display)
                 (lambda (_) (ert-fail "Must not open an unavailable server"))))
        (should-error (markdown-preview-session-open) :type 'user-error)))))

(ert-deftest markdown-preview-session-keeps-widgets-per-source ()
  (let ((source-a (generate-new-buffer " *preview-source-a*"))
        (source-b (generate-new-buffer " *preview-source-b*"))
        (features (cons 'xwidget features))
        views current-widget installed navigated)
    (unwind-protect
        (cl-letf (((symbol-function 'xwidget-live-p) #'buffer-live-p)
                  ((symbol-function 'xwidget-buffer) #'identity)
                  ((symbol-function 'xwidget-webkit-current-session)
                   (lambda () current-widget))
                  ((symbol-function 'xwidget-webkit-new-session)
                   (lambda (_) (setq current-widget (generate-new-buffer " *preview-view*"))
                     (push current-widget views) (set-buffer current-widget)))
                  ((symbol-function 'xwidget-webkit-goto-uri)
                   (lambda (widget _) (push widget navigated)))
                  ((symbol-function 'pop-to-buffer) #'set-buffer)
                  ((symbol-function 'markdown-github-preview--enable-autoscroll)
                   (lambda (widget) (push widget installed))))
          (with-current-buffer source-a (markdown-preview-session--display "a"))
          (let ((widget-a current-widget))
            (with-current-buffer source-b (markdown-preview-session--display "b"))
            (should-not (eq widget-a current-widget))
            (with-current-buffer source-a (markdown-preview-session--display "a"))
            (should (eq (car installed) widget-a))
            (should (eq (car navigated) widget-a))
            (should (= (length views) 2))
            (kill-buffer widget-a)
            (with-current-buffer source-a (markdown-preview-session--display "a"))
            (should (= (length views) 3))))
      (mapc (lambda (buffer) (when (buffer-live-p buffer) (kill-buffer buffer)))
            (append views (list source-a source-b))))))
